package Menu;

import Menu.Menu;
import Menu.acciones_BD;
import java.sql.ResultSet;
import java.sql.SQLException;
import javafx.geometry.HPos;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class Altas extends javax.swing.JFrame {

    /**
     * Creates new form Altas
     */
    acciones_BD aBD= new acciones_BD();
    acciones_altas aca = new acciones_altas();
    
    ResultSet res; 
    ResultSet res1;
    DefaultTableModel modeloTabla;
   
    public Altas() {
         modeloTabla = new DefaultTableModel(null, getColumnas());
       
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
     private String [] getColumnas(){
        String columna []= new String []{"No_Motor","Tipo","Nombre","Cilindraje"};
        
        return columna;
    }
    
    private void setFilas(){
        try{
            
            ResultSet rst=aBD.modivehiculo();
            
            Object datos [] = new Object [4];
            while(rst.next()){
                for (int i = 0; i <4; i++){
                    datos[i] = rst.getObject(i + 1);
                }
                modeloTabla.addRow(datos);
            }
            rst.close();
        } catch (SQLException ex){
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }
    
    private void limpiartabla(){
        try {
            for (int i = 0; i < tabla.getRowCount();i++){
                modeloTabla.removeRow(i);
                i-=1;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        corrocionG = new javax.swing.ButtonGroup();
        respaldoG = new javax.swing.ButtonGroup();
        roboG = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        deshacer = new javax.swing.JLabel();
        rehacer = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        numero = new javax.swing.JTextField();
        tipo = new javax.swing.JTextField();
        nom = new javax.swing.JTextField();
        cmbcil = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        macor = new javax.swing.JTextField();
        pintura = new javax.swing.JTextField();
        corrsi = new javax.swing.JRadioButton();
        corrno = new javax.swing.JRadioButton();
        respsi = new javax.swing.JRadioButton();
        respno = new javax.swing.JRadioButton();
        robosi = new javax.swing.JRadioButton();
        robono = new javax.swing.JRadioButton();
        aceptar = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        Nuse = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        Seguro = new javax.swing.JTextField();
        garantia = new javax.swing.JComboBox<>();
        carretera = new javax.swing.JTextField();
        ciudad = new javax.swing.JTextField();
        potencia = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        combinado = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        km15 = new javax.swing.JTextField();
        km30 = new javax.swing.JTextField();
        km45 = new javax.swing.JTextField();
        km60 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel32 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 218));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-chevron-left.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1313, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, -1));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        deshacer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-deshacer-48.png"))); // NOI18N
        deshacer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deshacerMouseClicked(evt);
            }
        });

        rehacer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-rehacer-48.png"))); // NOI18N
        rehacer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rehacerMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(deshacer)
                .addGap(18, 18, 18)
                .addComponent(rehacer)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deshacer)
                    .addComponent(rehacer))
                .addContainerGap(302, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, 510));

        jLabel1.setText("Numero de Motor");

        jLabel2.setText("Tipo");

        jLabel3.setText("Nombre");

        jLabel4.setText("Cilindraje");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Adicionales");

        cmbcil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "4", "8", "12" }));

        jLabel5.setText("Matenimiento Correctivo");

        jLabel9.setText("Robo");

        jLabel10.setText("Corrocion");

        jLabel11.setText("Pintura");

        jLabel12.setText("Garantia");

        jLabel13.setText("Respaldo");

        corrocionG.add(corrsi);
        corrsi.setText("Si");

        corrocionG.add(corrno);
        corrno.setText("No");

        respaldoG.add(respsi);
        respsi.setText("Si");

        respaldoG.add(respno);
        respno.setText("No");

        roboG.add(robosi);
        robosi.setText("Si");

        roboG.add(robono);
        robono.setText("No");

        aceptar.setText("Aceptar");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });

        jLabel14.setText("Numero de Serie");

        jLabel15.setText("Seguro");

        garantia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 Año", "2 Años", "4 Años", "5 Años", " " }));

        ciudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ciudadActionPerformed(evt);
            }
        });

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("Rendimiento");

        jLabel17.setText("Carretera");

        jLabel18.setText("Combinado");

        jLabel19.setText("Ciudad");

        jLabel20.setText("Potencia");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel21.setText("Vehiculo");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel22.setText("Rendimiento");

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel23.setText("30 Mil Km");

        jLabel24.setText("15 Mil Km");

        jLabel25.setText("45 Mil Km");

        jLabel26.setText("60 Mil Km");

        jLabel27.setText("Hp");

        jLabel28.setText("$");

        jLabel29.setText("$");

        jLabel30.setText("$");

        jLabel31.setText("$");

        jLabel7.setText("KM/L");

        jLabel34.setText("KM/L");

        jLabel35.setText("KM/L");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel14)
                        .addGap(177, 177, 177)
                        .addComponent(jLabel15)
                        .addGap(116, 116, 116)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel5))
                            .addComponent(macor, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1))
                                .addGap(31, 31, 31)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbcil, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(115, 115, 115)
                                .addComponent(jLabel21)))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel20)
                            .addComponent(jLabel19))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(potencia, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel27))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(combinado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                                    .addComponent(carretera, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ciudad, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel23)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(km30))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel24)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(km15))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel26)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(km60))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel25)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(km45, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel28)
                                    .addComponent(jLabel29)
                                    .addComponent(jLabel30)
                                    .addComponent(jLabel31)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(jLabel22))))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                            .addGap(55, 55, 55)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Nuse, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(corrsi)
                                        .addComponent(corrno)
                                        .addComponent(jLabel10))
                                    .addGap(45, 45, 45)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel13)
                                        .addComponent(respsi)
                                        .addComponent(respno))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(Seguro, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(145, 145, 145))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9)
                                        .addComponent(robosi)
                                        .addComponent(robono))
                                    .addGap(35, 35, 35)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel12)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                            .addComponent(garantia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(71, 71, 71)
                                            .addComponent(pintura, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(aceptar))))))
                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 792, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(318, 318, 318)
                        .addComponent(jLabel8)))
                .addContainerGap(8, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel21))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel4))
                            .addComponent(cmbcil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel22))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel19)
                                            .addComponent(ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel34))
                                        .addGap(29, 29, 29)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel17)
                                            .addComponent(carretera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7))
                                        .addGap(23, 23, 23)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel18)
                                            .addComponent(combinado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel35))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel20)
                                            .addComponent(potencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel27)))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel24)
                                            .addComponent(km15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel28))
                                        .addGap(34, 34, 34)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel23)
                                            .addComponent(km30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel29))
                                        .addGap(24, 24, 24)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel25)
                                            .addComponent(km45, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel30))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel26)
                                            .addComponent(km60, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel31)))))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nuse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Seguro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(macor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel13)
                            .addComponent(jLabel9)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(corrsi)
                                    .addComponent(respsi))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(corrno)
                                    .addComponent(respno)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(robosi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(robono))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(23, 23, 23)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(garantia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pintura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(aceptar))))
                .addGap(94, 94, 94))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 800, 510));

        tabla.setModel(modeloTabla);
        jScrollPane1.setViewportView(tabla);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 80, 400, -1));

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel32.setText("Registros ");
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 40, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        int dialog = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null, "Seguro desea regresar al menu.\n El progreso se perdera", "Exit", dialog);
        if (result==0){
            this.dispose();
            Menu menu = new Menu();
            menu.show();
        }
    }//GEN-LAST:event_jLabel6MouseClicked
    int xx,xy;
    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        JOptionPane.showMessageDialog(this,aBD.conexioBD());
        limpiartabla();
        setFilas();
    }//GEN-LAST:event_formWindowOpened

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        int res=JOptionPane.showConfirmDialog(null,"Desea Guardar sus Datos");
        if(JOptionPane.OK_OPTION==res){
          /*inicia el aceptar*/
          int corrocion = 0, respaldo = 0, robo = 0;
          
            if (corrsi.isSelected()) 
                corrocion =1;
            
            if(respsi.isSelected())
                respaldo = 1;
            
            if(robosi.isSelected())
                robo = 1;
            
            System.out.println("------------------------------INSERTANDO EN LA BD---------------------------------------");
            //automovil
            System.out.println(aBD.agregar1BD(Integer.parseInt(numero.getText()), 
                    tipo.getText(), nom.getText(), Integer.parseInt((String) cmbcil.getSelectedItem())));
            
            //adicionales
            System.out.println(aBD.agregar2BD(Integer.parseInt(Nuse.getText()), Seguro.getText(),
                    macor.getText(), robo, corrocion, pintura.getText(), (String) garantia.getSelectedItem(), 
                            respaldo,Integer.parseInt(numero.getText())));
            //Rendimineto
            System.out.println(aBD.agregar3BD(ciudad.getText(), 
                    carretera.getText(),combinado.getText(), 
                    potencia.getText(),Integer.parseInt(numero.getText())));
            //servicios
            System.out.println(aBD.services(Integer.parseInt(numero.getText()), 
                    Float.parseFloat(km15.getText()), Float.parseFloat(km30.getText()),
                    Float.parseFloat(km45.getText()), Float.parseFloat(km60.getText())));
            System.out.println("*****************+++++++++++++++++FIN+++++***********************++++++++++++++++");
            /*
                           __                             _                 _    
                          / _|                           | |               | |   
              ___   __ _ | |_   ___    ___   _ __    ___ | |_   __ _   ___ | | __
             / __| / _` ||  _| / _ \  / _ \ | '_ \  / __|| __| / _` | / __|| |/ /
             \__ \| (_| || |  |  __/ | (_) || | | | \__ \| |_ | (_| || (__ |   < 
             |___/ \__,_||_|   \___|  \___/ |_| |_| |___/ \__| \__,_| \___||_|\_\
             
            */
            int co = 0, ro = 0, re = 0;
            if (corrsi.isSelected()) {
                co = 1;
            }else if(corrno.isSelected()){
                co = 0;
            }
       
            if(respsi.isSelected()){
                re = 1;
            }else if(respno.isSelected()){
                re = 0;
            } 
            
            if(robosi.isSelected()){
                ro = 1;
            }else if(robono.isSelected()){
                ro = 0;
            }
            int g = garantia.getSelectedIndex();
            String gg = String.valueOf(g);
            
            System.out.println("*********************************guardando en memoria para ctl+z**********************************************");
            aca.guardarAdicionalesMod(Integer.parseInt(Nuse.getText()), Seguro.getText(), macor.getText() , ro, co , 
                    pintura.getText(),gg ,re , Integer.parseInt(numero.getText()));
            
            aca.guardarRendimientoMod(Integer.parseInt(numero.getText()),ciudad.getText(),carretera.getText(),
                    combinado.getText(), potencia.getText(),Integer.parseInt(numero.getText()));
            
            aca.guardarServicioMod(Integer.parseInt(numero.getText()), Integer.parseInt(Nuse.getText()), Integer.parseInt(km15.getText()),
                    Integer.parseInt(km30.getText()), Integer.parseInt(km45.getText()), Integer.parseInt(km60.getText()));
            
            aca.guardarVehiculoMod(Integer.parseInt(numero.getText()), tipo.getText(), nom.getText(), cmbcil.getSelectedIndex());
            
            
            /*
                _____  _                     _                 _                _   ______  _        _      _ 
               /  __ \| |                   (_)               | |              | |  |  ___|(_)      | |    | |
               | /  \/| |  ___   __ _  _ __  _  _ __    __ _  | |_   ___ __  __| |_ | |_    _   ___ | |  __| |
               | |    | | / _ \ / _` || '__|| || '_ \  / _` | | __| / _ \\ \/ /| __||  _|  | | / _ \| | / _` |
               | \__/\| ||  __/| (_| || |   | || | | || (_| | | |_ |  __/ >  < | |_ | |    | ||  __/| || (_| |
                \____/|_| \___| \__,_||_|   |_||_| |_| \__, |  \__| \___|/_/\_\ \__|\_|    |_| \___||_| \__,_|
                                                        __/ |                                                 
                                                       |___/                        
            */
            
            numero.setText("");
            tipo.setText("");
            nom.setText("");
            Nuse.setText("");
            Seguro.setText("");
            macor.setText("");
            pintura.setText("");
            numero.setText("");
            km15.setText("");
            km30.setText("");
            km45.setText("");
            km60.setText("");
            ciudad.setText("");
            carretera.setText("");
            potencia.setText("");
            combinado.setText("");
            corrocionG.clearSelection();
            roboG.clearSelection();
            respaldoG.clearSelection();
            cmbcil.setSelectedIndex(0);
            garantia.setSelectedIndex(0);
            limpiartabla();
            setFilas();
        }
        
        else if (JOptionPane.NO_OPTION==res){
            JOptionPane.showMessageDialog(null,"No se han guardado los datos");
        }
        else if (JOptionPane.CANCEL_OPTION==res){

        }
    }//GEN-LAST:event_aceptarActionPerformed

    private void ciudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ciudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ciudadActionPerformed

    private void deshacerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deshacerMouseClicked
        // TODO add your handling code here:
            //guardo los datos en la lista para deshacer adicionales
            /*
                _____ _        _           ______
               / ____| |      | |    _    |___  /
              | |    | |_ _ __| |  _| |_     / / 
              | |    | __| '__| | |_   _|   / /  
              | |____| |_| |  | |   |_|    / /__ 
               \_____|\__|_|  |_|         /_____|

            */
          try {
                int ro = 0, re=0, co=0;
                pintura.setText(aca.pintura());
                macor.setText(aca.mantoCorrectivo());
                Seguro.setText(aca.Seguro());
                Nuse.setText(String.valueOf(aca.noSerieAd()));
                
                if (aca.saveCorrocion.size() == 0) {
                    corrocionG.clearSelection();
                }else{
                    if (aca.corrocion() == 1) {
                        corrsi.setSelected(true);
                        corrno.setSelected(false);
                        co=1;
                    }else{
                        corrno.setSelected(true);
                        corrsi.setSelected(false);
                    }
                }
                
                if (aca.saveRobo.size() == 0) {
                    roboG.clearSelection();
                }else{ 
                    if (aca.robo()== 1) {
                        robosi.setSelected(true);
                        robono.setSelected(false);
                        ro=1;
                    }else{
                        robosi.setSelected(false);
                        robono.setSelected(true);
                    }
                }
                
                if (aca.saveRespaldo.size() == 0) {
                    respaldoG.clearSelection();
                } else{ 
                    if (aca.respaldo() == 1) {
                        respsi.setSelected(true);
                        respno.setSelected(false);
                        re=1;
                    }else{
                        respsi.setSelected(false);
                        respno.setSelected(true);
                    }
                }
                
                potencia.setText(aca.rendPotencia());
                combinado.setText(aca.rendCombinado());
                carretera.setText(aca.rendCarretera());
                ciudad.setText(aca.rendCiudad());
                
                km60.setText(String.valueOf(aca.mover60()));
                km45.setText(String.valueOf(aca.mover45()));
                km30.setText(String.valueOf(aca.mover30()));
                km15.setText(String.valueOf(aca.mover15()));
                
                nom.setText(aca.moverNombre());
                tipo.setText(aca.moverTipo());
                numero.setText(String.valueOf(aca.moverNoMotor()));
                garantia.setSelectedIndex(Integer.parseInt(aca.garantia()));
                
                int g = garantia.getSelectedIndex();
                String gg = String.valueOf(g);
           
                
                 aca.guardarAdicionalesModRetorno(Integer.parseInt(Nuse.getText()), Seguro.getText(), macor.getText() , ro, co , 
                    pintura.getText(),gg ,re , Integer.parseInt(numero.getText()));
            
                 aca.guardarRendimientoModRetorno(Integer.parseInt(numero.getText()),ciudad.getText(),carretera.getText(),
                    combinado.getText(), potencia.getText(),Integer.parseInt(numero.getText()));
            
                 aca.guardarServicioModRetorno(Integer.parseInt(numero.getText()), Integer.parseInt(Nuse.getText()), Integer.parseInt(km15.getText()),
                    Integer.parseInt(km30.getText()), Integer.parseInt(km45.getText()), Integer.parseInt(km60.getText()));
            
                 aca.guardarVehiculoModRetorno(Integer.parseInt(numero.getText()), tipo.getText(), nom.getText(), cmbcil.getSelectedIndex());
           
                 
                 System.out.println("corrocion tam: "+aca.saveCorrocionR.size()+"----garantia Tam: "+aca.saveGarantiaR.size());
                
                aBD.eliminarProducto(Integer.parseInt(numero.getText()));
                limpiartabla();
                setFilas();
        } catch (Exception e) {
              System.out.println("Errot CTL + Z: "+e.getMessage());
        }
                
    }//GEN-LAST:event_deshacerMouseClicked

    private void rehacerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rehacerMouseClicked
        // TODO add your handling code here:
        
        /*

            _____ _______ _               __     __
           / ____|__   __| |         _    \ \   / /
          | |       | |  | |       _| |_   \ \_/ / 
          | |       | |  | |      |_   _|   \   /  
          | |____   | |  | |____    |_|      | |   
           \_____|  |_|  |______|            |_|   

        */
        
          /*inicia el aceptar*/
         
            if (aca.saveCorrocionR.isEmpty()) {
                        numero.setText("");
                        tipo.setText("");
                        nom.setText("");
                        Nuse.setText("");
                        Seguro.setText("");
                        macor.setText("");
                        pintura.setText("");
                        numero.setText("");
                        km15.setText("");
                        km30.setText("");
                        km45.setText("");
                        km60.setText("");
                        ciudad.setText("");
                        carretera.setText("");
                        potencia.setText("");
                        combinado.setText("");
                        corrocionG.clearSelection();
                        roboG.clearSelection();
                        respaldoG.clearSelection();
                        cmbcil.setSelectedIndex(0);
                        garantia.setSelectedIndex(0);

             }else{
                int robo = 0, corrocion = 0, respaldo=0;
                pintura.setText(aca.pinturaR());
                macor.setText(aca.mantoCorrectivoR());
                Seguro.setText(aca.SeguroR());
                Nuse.setText(String.valueOf(aca.noSerieAdR()));
                
                if (aca.saveCorrocionR.size() == 0) {
                    corrocionG.clearSelection();
                }else{
                    if (aca.corrocionR()== 1) {
                        corrsi.setSelected(true);
                        corrno.setSelected(false);
                        corrocion = 1;
                    }else{
                        corrno.setSelected(true);
                        corrsi.setSelected(false);
                    }
                }
                
                if (aca.saveRoboR.size() == 0) {
                    roboG.clearSelection();
                }else{ 
                    if (aca.roboR()== 1) {
                        robo = 1;
                        robosi.setSelected(true);
                        robono.setSelected(false);
                    }else{
                        robosi.setSelected(false);
                        robono.setSelected(true);
                    }
                }
                
                if (aca.saveRespaldoR.size() == 0) {
                    respaldoG.clearSelection();
                } else{ 
                    if (aca.respaldoR()== 1) {
                        respsi.setSelected(true);
                        respno.setSelected(false);
                        respaldo = 1;
                    }else{
                        respsi.setSelected(false);
                        respno.setSelected(true);
                    }
                }
                
                potencia.setText(aca.rendPotenciaR());
                combinado.setText(aca.rendCombinadoR());
                carretera.setText(aca.rendCarreteraR());
                ciudad.setText(aca.rendCiudadR());
                
                km60.setText(String.valueOf(aca.mover60R()));
                km45.setText(String.valueOf(aca.mover45R()));
                km30.setText(String.valueOf(aca.mover30R()));
                km15.setText(String.valueOf(aca.mover15R()));
                
                nom.setText(aca.moverNombreRetorno());
                tipo.setText(aca.moverTipoRetorno());
                numero.setText(String.valueOf(aca.moverNoMotorRetorno()));
                
                garantia.setSelectedIndex(Integer.parseInt(aca.garantiaR()));
                
                int g = garantia.getSelectedIndex();
                String gg = String.valueOf(g);
           
                      
                aca.guardarAdicionalesMod(Integer.parseInt(Nuse.getText()), Seguro.getText(), macor.getText() , robo, corrocion , 
                    pintura.getText(),gg ,respaldo , Integer.parseInt(numero.getText()));
            
                aca.guardarRendimientoMod(Integer.parseInt(numero.getText()),ciudad.getText(),carretera.getText(),
                        combinado.getText(), potencia.getText(),Integer.parseInt(numero.getText()));

                aca.guardarServicioMod(Integer.parseInt(numero.getText()), Integer.parseInt(Nuse.getText()), Integer.parseInt(km15.getText()),
                        Integer.parseInt(km30.getText()), Integer.parseInt(km45.getText()), Integer.parseInt(km60.getText()));

                aca.guardarVehiculoMod(Integer.parseInt(numero.getText()), tipo.getText(), nom.getText(), cmbcil.getSelectedIndex());

         
                
                System.out.println("---------------------------INSERCIONES---------------------------------------");
                      //automovil
                      System.out.println(aBD.agregar1BD(Integer.parseInt(numero.getText()), 
                              tipo.getText(), nom.getText(), Integer.parseInt((String) cmbcil.getSelectedItem())));

                      //adicionales
                      System.out.println(aBD.agregar2BD(Integer.parseInt(Nuse.getText()), Seguro.getText(),
                              macor.getText(), robo, corrocion, pintura.getText(), (String) garantia.getSelectedItem(), 
                                      respaldo,Integer.parseInt(numero.getText())));
                      //Rendimineto
                      System.out.println(aBD.agregar3BD(ciudad.getText(), 
                              carretera.getText(),combinado.getText(), 
                              potencia.getText(),Integer.parseInt(numero.getText())));
                      //servicios
                      System.out.println(aBD.services(Integer.parseInt(numero.getText()), 
                              Float.parseFloat(km15.getText()), Float.parseFloat(km30.getText()),
                              Float.parseFloat(km45.getText()), Float.parseFloat(km60.getText())));
                     
                 System.out.println("*****************++++++++++++FIN INCERCIONES++++++++++***********************++++++++++++++++");
                     
                      limpiartabla();
                      setFilas();
             }
                /*System.out.println("-------------------------------------------CTL+Y------------------------------------------");
                String paintt =aca.pinturaR();
                String mantoCorrectivo = aca.mantoCorrectivoR();
                String seguro= aca.SeguroR();
                int numeroSerie= aca.noSerieAdR();
                
                String potenciaa = aca.rendPotenciaR();
                String combinadoo = aca.rendCombinadoR();
                String carreteraa = aca.rendCarreteraR();
                String ciudadd = aca.rendCiudadR();
                
                int km6= aca.mover60R(), km4=aca.mover45R(), km3=aca.mover30R(), km1=aca.mover15R();
                
                String nombre = aca.moverNombreRetorno();
                int numeroMotor= aca.moverNoMotorRetorno();
                String garantía = aca.garantiaR();

                int corrocion = aca.corrocionR();
                int robo = aca.roboR(); 
                int respaldo = aca.respaldoR();
                
                System.out.println(""+paintt+"\n"
                        +mantoCorrectivo
                +"\n"+seguro
                +"\n"+numeroSerie
                +"\n"+potenciaa
                +"\n"+combinadoo
                +"\n"+carreteraa
                +"\n"+ciudadd
                +"\n"+km6+""+km4+""+km3+""+km1
                +"\n"+nombre
                +"\n"+numeroMotor
                +"\n"+garantía
                +"\n"+corrocion
                +"\n"+robo
                +"\n"+respaldo);*/
      
    }//GEN-LAST:event_rehacerMouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Altas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Altas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Altas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Altas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Altas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Nuse;
    private javax.swing.JTextField Seguro;
    private javax.swing.JButton aceptar;
    private javax.swing.JTextField carretera;
    private javax.swing.JTextField ciudad;
    private javax.swing.JComboBox<String> cmbcil;
    private javax.swing.JTextField combinado;
    private javax.swing.JRadioButton corrno;
    private javax.swing.ButtonGroup corrocionG;
    private javax.swing.JRadioButton corrsi;
    private javax.swing.JLabel deshacer;
    private javax.swing.JComboBox<String> garantia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField km15;
    private javax.swing.JTextField km30;
    private javax.swing.JTextField km45;
    private javax.swing.JTextField km60;
    private javax.swing.JTextField macor;
    private javax.swing.JTextField nom;
    private javax.swing.JTextField numero;
    private javax.swing.JTextField pintura;
    private javax.swing.JTextField potencia;
    private javax.swing.JLabel rehacer;
    private javax.swing.ButtonGroup respaldoG;
    private javax.swing.JRadioButton respno;
    private javax.swing.JRadioButton respsi;
    private javax.swing.ButtonGroup roboG;
    private javax.swing.JRadioButton robono;
    private javax.swing.JRadioButton robosi;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField tipo;
    // End of variables declaration//GEN-END:variables
}
